version: '3'

services:
    dbapp:
        image: mysql:5
        restart: always
        volumes:
            - ./data:/var/lib/mysql
        env_file:
            - moodle_variables.env
        networks:
            - backendDB
        deploy:
            replicas: 1
            restart_policy:
                condition: any
        ports:
            - 3306:3306
    moodleapp:
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - dbapp:DB
        depends_on: 
            - dbapp
        restart: always
        volumes:
            - moodleapp-data:/var/moodledata
        ports:
            - 80:80
            - 443:443
        env_file:
            - moodle_variables.env
        networks:
            - backendDB
            - frontendWEB
        deploy:
            replicas: 1
            restart_policy:
                condition: any           
        depends_on: 
            - dbapp

volumes: 
    db-volume: 
    moodleapp-data:

networks:
    backendDB:
    frontendWEB:
