version: '3'

services:
    dbapp:
        image: mysql:8
        restart: always
        volumes:
            - ./data:/var/lib/mysql
        env_file:
            - moodle_variables.env
        networks:
            - backendDB
        deploy:
            replicas: 1
            restart_policy:
                condition: any
        ports:
            - 3306:3306
        healthcheck:
            test: mysqladmin $$MYSQL_DATABASE --user=$$MYSQL_USER --password='$$MYSQL_PASSWORD' ping"
            interval: 10s
            timeout: 2s
            retries: 10
    moodleapp:
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - dbapp:DB
        depends_on: 
            - dbapp
        restart: always
        volumes:
            - moodleapp-data:/var/moodledata
            - ./moodle:/var/www/html/
        ports:
            - 80:80
            - 443:443
        env_file:
            - moodle_variables.env
        networks:
            - backendDB
            - frontendWEB
        deploy:
            replicas: 1
            restart_policy:
                condition: any           
        depends_on: 
            - dbapp

volumes: 
    moodle:
    db-volume: 
    moodleapp-data:
    

networks:
    backendDB:
    frontendWEB:
